version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Set up yarn registry and NPM token
          command: |
            yarn config set registry "https://registry.npmjs.org/"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: flow
          command: yarn flow
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release
